name: Deploy static site to Azure Web App - MusicWebFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C53CF9168A1A4EC298449ED9E9A1B55C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7AA0EE5C24C84561907B6F7DCC856E25 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B5FE2F0539464D7D81825B12E67B3E94 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: MusicWebFront
          package: .
